# This is a basic workflow to help you get started with Actions          
name: "Scan image"
on: [push]

jobs:
  anchore_test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: anchore/scan-action@v2
      with:
        path: ./
        debug: true
